// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB46UzYJ6f4fdp8qRR0zSPRYwBI-zsS3i8',
    appId: '1:149102156630:web:182dccece97af21a0414f7',
    messagingSenderId: '149102156630',
    projectId: 'routemate-9e33b',
    authDomain: 'routemate-9e33b.firebaseapp.com',
    databaseURL: 'https://routemate-9e33b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'routemate-9e33b.firebasestorage.app',
    measurementId: 'G-873JN4ZWJN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADsw1K3MLLZNWOsWz2MNwGBcWJvNYt91Y',
    appId: '1:149102156630:android:8ec2e01390d3afd20414f7',
    messagingSenderId: '149102156630',
    projectId: 'routemate-9e33b',
    databaseURL: 'https://routemate-9e33b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'routemate-9e33b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJIUxjoOyAzUJPeWZErWmrTqxscs3s5cM',
    appId: '1:149102156630:ios:d0963c278e4a178a0414f7',
    messagingSenderId: '149102156630',
    projectId: 'routemate-9e33b',
    databaseURL: 'https://routemate-9e33b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'routemate-9e33b.firebasestorage.app',
    iosClientId: '149102156630-b7bm2dcjur5kv508ss4ekmtpttvhph4a.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJIUxjoOyAzUJPeWZErWmrTqxscs3s5cM',
    appId: '1:149102156630:ios:d0963c278e4a178a0414f7',
    messagingSenderId: '149102156630',
    projectId: 'routemate-9e33b',
    databaseURL: 'https://routemate-9e33b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'routemate-9e33b.firebasestorage.app',
    iosClientId: '149102156630-b7bm2dcjur5kv508ss4ekmtpttvhph4a.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB46UzYJ6f4fdp8qRR0zSPRYwBI-zsS3i8',
    appId: '1:149102156630:web:87891807eec2b8b60414f7',
    messagingSenderId: '149102156630',
    projectId: 'routemate-9e33b',
    authDomain: 'routemate-9e33b.firebaseapp.com',
    databaseURL: 'https://routemate-9e33b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'routemate-9e33b.firebasestorage.app',
    measurementId: 'G-1X5NE86Z7B',
  );
}
