name: route_mate_app
description: "RouteMate - Ứng dụng Hỗ trợ An toàn Phượt xe máy"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  
  # --- 1. LÕI HỆ THỐNG & API ---
  provider: ^6.1.2             
  flutter_dotenv: ^6.0.1       
  http: ^1.6.0                 
  google_generative_ai: ^0.4.6
  speech_to_text: ^7.3.0
  
  # --- 2. BACKEND FIREBASE (Giữ bản ổn định) ---
  firebase_core: ^2.30.0       
  firebase_database: ^10.4.0   
  cloud_firestore: ^4.17.0     
  firebase_messaging: ^14.7.10 
  cloud_functions: ^4.6.0      # Đã thêm cho M4, hạ version nhẹ để khớp với core 2.30.0
  
  # --- 3. BẢN ĐỒ & ĐỊNH VỊ GPS ---
  mapbox_maps_flutter: ^2.23.1 # Giữ thế độc tôn của Mapbox (Loại bỏ Google Maps của M4)
  flutter_map: ^6.1.0          
  latlong2: ^0.9.1             
  geolocator: ^12.0.0          # Giữ bản 12.0.0 để không bị xung đột
  
  # --- 4. TÍNH NĂNG SOS (Thêm từ M4) ---
  battery_plus: ^6.0.2         # Check pin (hạ version để fix lỗi js conflict)
  connectivity_plus: ^6.1.0    # Check mạng (Online/Offline)
  url_launcher: ^6.3.1         # Mở SMS Fallback
  
  # --- 5. GIAO DIỆN ---
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env